workflows:
  expo54-android-unsigned:
    name: Expo 54 Android Unsigned (Test Build)
    instance_type: mac_mini_m2
    max_build_duration: 60

    scripts:
      - name: Install deps
        script: npm ci

      - name: Expo prebuild (android)
        script: npx expo prebuild --platform android --clean --non-interactive

      - name: Build unsigned APK
        script: |
          cd android
          ./gradlew assembleRelease --stacktrace

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
