workflows:
  expo54-android:
    name: Expo 54 Android APK (stable verify)
    environment:
      node: 20
      java: 17
      vars: { CI: "true", EXPO_NO_TELEMETRY: "1" }
    scripts:
      - name: Install deps
        script: |
          rm -f pnpm-lock.yaml yarn.lock
          npm ci || npm install

      - name: Expo prebuild
        script: |
          npx expo prebuild --platform android --non-interactive --clean

      - name: Rewrite settings.gradle
        script: |
          cat > android/settings.gradle <<'GRADLE'
          pluginManagement { repositories { gradlePluginPortal(); google(); mavenCentral() } }
          dependencyResolutionManagement {
            repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
            repositories { google(); mavenCentral() }
          }
          rootProject.name = "app"
          include(":app")
          def rnGradlePlugin = new File("${rootDir}/../node_modules/react-native-gradle-plugin")
          if (rnGradlePlugin.exists()) { includeBuild(rnGradlePlugin) }
          def expoAutolinking = new File("${rootDir}/../node_modules/expo-modules-autolinking")
          if (expoAutolinking.exists()) { includeBuild(expoAutolinking) }
          GRADLE

      - name: Rewrite root build.gradle
        script: |
          cat > android/build.gradle <<'GRADLE'
          // Root-level build file
          buildscript {
            repositories { google(); mavenCentral() }
            dependencies {
              classpath("com.android.tools.build:gradle:8.5.2")
              classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.24")
              // ❌ Jangan tambah react-native-gradle-plugin di sini
            }
          }
          allprojects { repositories { google(); mavenCentral() } }
          GRADLE

      - name: Verify classpath versions (stable)
        script: bash ci_verify_gradle.sh

      - name: Build release APK
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease -x lint --stacktrace

    artifacts:
      - android/app/build/outputs/**/*.apk
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
        - $CM_BUILD_DIR/android/.gradle
        - $HOME/.gradle/caches
