workflows:
  react-native-android:
    name: React Native Android Signed
    environment:
      groups:
        - keystore
    scripts:
      - name: Decode keystore
        script: |
          mkdir -p android
          echo "$CM_KEYSTORE" | base64 --decode > "$CM_KEYSTORE_PATH"
          ls -lah android | sed -n 's/^/  /p'

      - name: Install dependencies
        script: |
          npm ci

      - name: Ensure android folder exists
        script: |
          if [ ! -d "android" ]; then
            echo "⚙️ Android folder not found. Running Expo prebuild..."
            npx expo prebuild --platform android --clean
          else
            echo "✅ Android folder exists."
          fi

      - name: Expo prebuild (android)
        script: |
          npx expo prebuild --platform android --clean

      - name: Build signed release APK
        script: |
          cd android
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$CM_KEYSTORE_PATH \
            -Pandroid.injected.signing.store.password=$CM_KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$CM_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$CM_KEY_PASSWORD

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
