workflows:
  expo54:
    name: "Expo SDK 54 Android APK"
    max_build_duration: 60
    environment:
      vars:
        NODE_VERSION: 20
        JAVA_VERSION: 17
        EXPO_NO_TELEMETRY: "1"
    scripts:
      - name: Install deps
        script: |
          rm -f yarn.lock package-lock.json pnpm-lock.yaml
          npm install
      - name: Expo prebuild (Android)
        script: |
          npx expo prebuild --platform android --non-interactive --clean
      - name: Build APK
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease --stacktrace
    artifacts:
      - android/app/build/outputs/**/*.apk
