workflows:
  expo54-android:
    name: Expo 54 Android APK (pinned Gradle 8.6)
    environment:
      node: 20
      java: 17
      vars:
        CI: "true"
        EXPO_NO_TELEMETRY: "1"
    scripts:
      - name: Install deps
        script: |
          rm -f pnpm-lock.yaml yarn.lock
          npm ci || npm install

      - name: Expo prebuild
        script: |
          npx expo prebuild --platform android --non-interactive --clean

      - name: Enforce Gradle wrapper 8.6
        script: |
          cd android
          ./gradlew --version || true
          ./gradlew wrapper --gradle-version 8.6 --distribution-type bin
          cat gradle/wrapper/gradle-wrapper.properties | sed -n '1,200p'

      - name: Verify classpath versions
        script: |
          grep -q 'com.android.tools.build:gradle:8.5.2' android/build.gradle || (echo "AGP versi salah" && exit 1)
          grep -q 'kotlin-gradle-plugin:1.9.24' android/build.gradle || (echo "Kotlin versi salah" && exit 1)
          if grep -q 'react-native-gradle-plugin' android/build.gradle; then echo "RN plugin tak boleh dalam classpath"; exit 1; fi

      - name: Build release APK
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease -x lint --stacktrace --warning-mode=all

    artifacts:
      - android/app/build/outputs/**/*.apk
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
        - $CM_BUILD_DIR/android/.gradle
        - $HOME/.gradle/caches
