workflows:
  expo54_android_apk:
    name: Expo 54 Android APK (SDK 54)
    max_build_duration: 60
    environment:
      vars:
        EXPO_NO_TELEMETRY: "1"
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
        - $CM_BUILD_DIR/android/.gradle
        - $HOME/.gradle/caches
    scripts:
      - name: Install deps
        script: |
          echo "Node: $(node -v || true)"
          # Pastikan node_modules wujud untuk plugin RN/Expo
          npm ci || npm install --legacy-peer-deps

      - name: Expo prebuild (Android)
        script: |
          npx expo prebuild --platform android --non-interactive --clean
          test -f android/settings.gradle || { echo "android/settings.gradle missing after prebuild"; exit 1; }

      - name: Build APK
        script: |
          cd android
          ./gradlew --no-daemon clean
          ./gradlew --no-daemon assembleRelease -x lint --stacktrace

    artifacts:
      - android/app/build/outputs/**/*.apk
