workflows:
  expo54-android:
    name: Expo 54 Android (Signed APK)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      # GANTI 'MY_RELEASE_KEY' dgn nama keystore reference yang kau upload
      # di App settings → Code signing → Android keystores
      android_signing:
        - MY_RELEASE_KEY

    scripts:
      - name: Install deps
        script: npm ci

      - name: Expo prebuild (android)
        script: npx expo prebuild --platform android --clean --non-interactive

      - name: Build signed release APK
        script: |
          cd android
          ./gradlew assembleRelease --stacktrace

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
