workflows:
  debug-apk:
    name: Debug APK Build (Expo 54)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        CI: true
        EXPO_NO_INTERACTIVE: 1
      node: 20.12.2
      java: 17
    scripts:
      - name: 🔧 Install dependencies
        script: |
          npm install -g expo-cli
          npm install
          npm install jetifier --save-dev || true

      - name: 🏗️ Prebuild Android (clean)
        script: |
          npx expo prebuild --platform android --clean
          cd android
          chmod +x gradlew

      - name: 🧩 Pin Gradle & Kotlin
        script: |
          cd android
          perl -pi -e 's#distributionUrl=.*#distributionUrl=https://services.gradle.org/distributions/gradle-8.6-bin.zip#g' gradle/wrapper/gradle-wrapper.properties
          if [ -f build.gradle ]; then
            perl -pi -e 's/ext\.kotlin_version\s*=.*/ext.kotlin_version = "1.9.22"/g' build.gradle || true
          fi

      - name: 🩹 Patch expo autolinking (extensions/extra)
        script: |
          PLUG_DIR="node_modules/expo-modules-autolinking/android/expo-gradle-plugin"
          if [ -d "$PLUG_DIR" ]; then
            find "$PLUG_DIR" -name "SettingsManager.kt" -print0 | while IFS= read -r -d '' f; do
              sed -i '' 's/\<extensions\>/project.extensions/g' "$f" || true
              sed -i '' 's/\<extra\>/project.extra/g' "$f" || true
            done
          fi

      - name: 🧹 Build Debug APK
        script: |
          cd android
          ./gradlew clean
          ./gradlew :app:assembleDebug --no-daemon --warning-mode all --stacktrace

    artifacts:
      - android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - $CM_EMAIL
        notify:
          success: true
          failure: true
