workflows:
  debug-apk:
    name: Debug APK Build (Expo 54)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        CI: true
        EXPO_NO_INTERACTIVE: 1
      node: 20.12.2
      java: 17
    scripts:
      - name: ðŸ”§ Install deps
        script: |
          npm install
          npx --yes jetify || true

      - name: ðŸ—ï¸ Prebuild Android (clean)
        script: |
          npx expo prebuild --platform android --clean
          cd android
          chmod +x gradlew

      - name: ðŸ§© Pin Gradle & Kotlin (Expo 54 serasi)
        script: |
          cd android
          # Gradle 8.6
          sed -i 's#^distributionUrl=.*#distributionUrl=https://services.gradle.org/distributions/gradle-8.6-bin.zip#g' gradle/wrapper/gradle-wrapper.properties
          # Kotlin plugin 1.9.22 (dua gaya fail disokong)
          if grep -q 'ext.kotlin_version' build.gradle 2>/dev/null; then
            sed -i 's/ext.kotlin_version.*/ext.kotlin_version = "1.9.22"/' build.gradle || true
          fi
          if grep -q 'org.jetbrains.kotlin.android' build.gradle 2>/dev/null; then
            sed -i 's/\(id "org.jetbrains.kotlin.android" version "\)[^"]*\(".*\)/\11.9.22\2/' build.gradle || true
          fi
          if [ -f build.gradle.kts ]; then
            if grep -q 'id("org.jetbrains.kotlin.android")' build.gradle.kts; then
              sed -i 's/\(id("org.jetbrains.kotlin.android") version "\)[^"]*\(".*\)/\11.9.22\2/' build.gradle.kts || true
            fi
          fi

      - name: ðŸ©¹ Patch expo autolinking (extensions/extra)
        script: |
          PLUG_DIR="node_modules/expo-modules-autolinking/android/expo-gradle-plugin"
          if [ -d "$PLUG_DIR" ]; then
            find "$PLUG_DIR" -name "SettingsManager.kt" -print0 | while IFS= read -r -d '' f; do
              sed -i 's/\<extensions\>/project.extensions/g' "$f" || true
              sed -i 's/\<extra\>/project.extra/g' "$f" || true
              echo "Patched: $f"
            done
          fi

      - name: ðŸ§¹ Clean & Build Debug APK
        script: |
          cd android
          ./gradlew clean
          ./gradlew :app:assembleDebug --no-daemon --warning-mode all --stacktrace

    artifacts:
      - android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - $CM_EMAIL
        notify:
          success: true
          failure: true
